# @Author: Roni Laukkarinen
# @Date:   2025-04-13 18:54:02
# @Last Modified by:   Roni Laukkarinen
# @Last Modified time: 2025-04-13 23:14:07
# Remove version as it's obsolete in newer Docker Compose

version: '3.8'

services:
  backend:
    container_name: eventia-backend-dev
    build:
      context: ./eventia-backend
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    volumes:
      - ./eventia-backend:/app
    environment:
      - FLASK_ENV=development
      - PORT=3003
      - MONGO_URI=mongodb://mongodb:27017/eventia
      - ADMIN_TOKEN=devsecrettoken123
    depends_on:
      - mongodb
    networks:
      - eventia-network

  frontend:
    container_name: eventia-frontend-dev
    build:
      context: ./eventia-ticketing-flow
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./eventia-ticketing-flow:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3003/api
    depends_on:
      - backend
    networks:
      - eventia-network

  mongodb:
    container_name: eventia-mongodb-dev
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - eventia-network

  mongo-express:
    image: mongo-express:latest
    container_name: eventia-mongo-express-dev
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
      # Add these configurations to show all fields
      - ME_CONFIG_OPTIONS_EDITMODE=true
      - ME_CONFIG_OPTIONS_EDITABLE=true
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_OPTIONS_NO_DELETE=false
      # Disable field sanitization to show all fields
      - ME_CONFIG_REQUEST_SKIP_SAFE_LIMIT=true
      - ME_CONFIG_REQUEST_SIZE_LIMIT=100mb
      - ME_CONFIG_SITE_GRIDFS_ENABLED=true
      - ME_CONFIG_SITE_SESSION_SECRET=eventia-secret-key-123
      - ME_CONFIG_SITE_SSL_ENABLED=false
      # These settings ensure all fields are displayed
      - VCAP_APP_HOST=0.0.0.0
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
    depends_on:
      - mongodb
    networks:
      - eventia-network
    restart: on-failure

  nginx:
    container_name: eventia-nginx-dev
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - mongo-express
      - frontend
      - backend
    networks:
      - eventia-network

networks:
  eventia-network:
    driver: bridge

volumes:
  mongodb_data_dev: