global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  - "rules/backend_alerts.yml"

scrape_configs:
  - job_name: 'eventia-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:3002']
    
  - job_name: 'eventia-frontend'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['localhost:3000']
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100'] 